# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ./src/toolboxal_ui.h
SOURCES += ./src/main.cpp \
    ./src/toolboxal_ui.cpp \
    ./src/entrypoint.cpp
FORMS += ./src/toolboxal_ui.ui
RESOURCES += toolboxal_ui.qrc
