# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = UI
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
INCLUDEPATH += ./src
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(Toolboxal.pri)
